### ISSUE TITLE
GeckoLib support

### ISSUE THREAD

**Issue by Soleil-des-chats** [PSGitHubUser1/Creators-Essentials#1]
### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature <a href='https://github.com/PSGitHubUser1/Creators-Essentials/issues' target='_blank'>is not already asked.</a>
- [X] I have checked that this feature is not already implemented.

### Feature description

Can you bring back the GeckoLib support ? It is very usefull for animating and can’t really without it. Nerdy’s mcreator plugin is only for forge.

**Comment by PSGitHubUser1** [comment]
That's the issue. I don't know anything but APIs. 

Geckolib is hard as you need to add Procedures too.. & I guess know nothing about procedures... Also, it won't make any sense that I added API but not procedures, then it is just waste of time too.. so yeah... 

Just waiting for a PR (who makes a PR that means he/she is Godsent, atleast for me though)
